Repository redhat-plumbers/systemd-rhel8, pull requests merged in 2021-09, with the labels that each got.

#211 (#1850986) Fix LGTM build
  src/network/netdev/netdev.c
  src/network/networkd-network.c
Labels: ci-waived, rhel-8.5.0

#215 (#1946943) basic/cap-list: parse/print numerical capabilities
  src/basic/cap-list.c
  src/test/test-cap-list.c
Labels: rhel-8.3.0

#214 (#1946943) basic/cap-list: parse/print numerical capabilities
  src/basic/cap-list.c
  src/test/test-cap-list.c
Labels: ci-waived, rhel-8.2.0
