Repository redhat-plumbers/systemd-rhel8, pull requests merged in 2022-09, with the labels that each got.

#319 (#2110545) resolved: pin stream while calling callbacks for it
  src/resolve/resolved-dns-stream.c
Labels: needs-ci, rhel-8.1.0, ci-waived

#318 (#2110546) resolved: pin stream while calling callbacks for it
  src/resolve/resolved-dns-stream.c
Labels: needs-ci, ci-waived, rhel-8.2.0

#327 (#2127170) core: move reset_arguments() to the end of main's finish
  src/core/main.c
Labels: needs-ci, rhel-8.7.0

#317 (#2110547) resolved: pin stream while calling callbacks for it
  src/resolve/resolved-dns-stream.c
Labels: ci-waived, rhel-8.4.0

#316 (#2110548) resolved: pin stream while calling callbacks for it
  src/resolve/resolved-dns-stream.c
Labels: needs-ci, ci-waived, rhel-8.6.0

#328 (#2127171) core: move reset_arguments() to the end of main's finish
  src/core/main.c
Labels: ci-waived, rhel-8.6.0

#329 (#2127172) core: move reset_arguments() to the end of main's finish
  src/core/main.c
Labels: ci-waived, rhel-8.4.0

#331 (#2110547) test-procfs-util: skip test on certain errors
  src/shared/tests.c
  src/shared/tests.h
  src/test/test-procfs-util.c
Labels: needs-ci, ci-waived, rhel-8.4.0
