Repository redhat-plumbers/systemd-rhel8, pull requests merged in 2022-11, with the labels that each got.

#337 (#2139390) time-util: fix buffer-over-run
  src/basic/time-util.c
  src/test/test-time-util.c
Labels: needs-ci, rhel-8.7.0

#334 (#2127170) core: move reset_arguments() to the end of main's finish
  src/core/main.c
Labels: needs-ci, rhel-8.7.0

#342 (#2143100) basic: recognize pdfs filesystem as a network filesystem
  src/basic/mount-util.c
Labels: ci-waived, rhel-8.7.0

#341 (#2143101) basic: recognize pdfs filesystem as a network filesystem
  src/basic/mount-util.c
Labels: ci-waived, rhel-8.6.0

#340 (#2143102) basic: recognize pdfs filesystem as a network filesystem
  src/basic/mount-util.c
Labels: ci-waived, rhel-8.4.0

#339 (#2143103) basic: recognize pdfs filesystem as a network filesystem
  src/basic/mount-util.c
Labels: ci-waived, rhel-8.2.0
