Repository redhat-plumbers/systemd-rhel8, pull requests merged in 2023-07, with the labels that each got.

#389 (#2158724) core/mount: escape invalid UTF8 char in dbus reply
  src/core/dbus-mount.c
Labels: needs-ci

#405 (#2223602) Better handle session leader information
  src/login/logind-dbus.c
  src/login/logind-session.c
  src/login/logind-session.h
Labels: needs-manual-merge, rhel-8.8.0

#404 (#2223582) test-login: skip consistency checks when logind is not active
  src/libsystemd/sd-login/test-login.c
Labels: needs-acks
