Repository redhat-plumbers/systemd-rhel8, pull requests merged in 2023-03, with the labels that each got.

#366 (#2174645) Make sure journalctl --flush does not hang
  src/journal/journald-server.c
Labels: ci-waived, rhel-8.8.0

#365 (#2174645) Make sure journalctl --flush does not hang
  src/journal/journald-server.c
Labels: ci-waived

#367 (#2178002) Detect ARM64 Hyper-V guests
  src/basic/virt.c
Labels: rhel-8.7.0, needs-manual-merge

#374 (#2179309) test: make TEST-35-LOGIN stable again
  test/TEST-35-LOGIN/testsuite.sh
  test/test-functions
Labels: ci-waived
